version: '3'

services:
  js:
    image: node:18
    container_name: js
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]
    networks:
      - default

networks:
  default:
    driver: bridge